before_install:
    # init xvfb
    # http://docs.travis-ci.com/user/gui-and-headless-browsers/
    - "export DISPLAY=:99.0 && sh -e /etc/init.d/xvfb start"
branches:
    only:
    - alpha
    - beta
    - cron
    - docker.base
    - docker.latest
    - master
    - publish
    - task
env:
    global:
    # this value is auto-created by shTravisCryptoAesEncryptYml
    - secure: NgsXL00Dmp+sxI+4scVIsYTQhwhtTAmhI6MzrDdmKnsWEQ0L+d3HWjr9HrWdVqnUemY+bhhiwgpZZt5CAu32iYZJun8Mc6/lE1ngCm4Og6jwyWp5edpy0dELtS/IO/j2FzUH1T7XYtRQH2h5Sk/TiKJH3WdeNp7+249aaqQGIynfi2Aker0Ac65qq0eRg7tnm55TVfTrcZgvoHD7G/PI2gTDvXB85PAImBWBpYHWo8gm+AU/y1MdKc1UKqUsJa/FlFrF3v7dgq+B4xEutAzWeRolX79PV8T27z3BvYyKk6lU3+qcogXe3AmtDWU1knN7cYExqt5beGNfvzcbEapwTnvBx8tl0bbefBcfoZB7pfGg0LprMVBdseHeS+BpdTvjBx8bZBFAIAvFs9y7tVOPJaC0vr9ki6+8UgdtZC5G3v5mwl08mVXMboh2c4rCHFb7wEV5m5mF/Tl4KSGC4HmzCa8iomzrcrpwH/iL1b1zy5RJLqFloiviR9vh58kM0zabJTu6g7HueKjCYIzk00ICsxtkTXGnXqrELS+pAIYSJmtvjZhDpo0IduXkVeT+c/KaU52nksLQeOV2GeEjBKghWEHdfLn7o7BlRyO4umyC222kX97prlaJd1a3HCyAZBXYoOUxpyCksCBzTEBzYFrIuvqP8+KldJLJsMEQRhAJ4i4= # CRYPTO_AES_KEY
    # this value is auto-created by shTravisCryptoAesEncryptYml

language:
    - node_js
node_js:
    - 6
    # - node
script:
    - npm run build-ci
services:
    - docker
# http://docs.travis-ci.com/user/workers/container-based-infrastructure
sudo:
    false
